### ISSUE TITLE
Ansible-galaxy release GH action is broken (HTTP 403)

### ISSUE THREAD

**Issue by t0mk** [equinix-labs/ansible-collection-equinix#127]
I tried to do a new release v0.3.0 and the github action that publsihes to AG failed with HTTP 403
https://github.com/equinix-labs/ansible-collection-equinix/actions/runs/6466670085/job/17555164588

Apparently, sth has changed in Galaxy, and we should regenerate the API key (?) @displague linked this thread a couple of days ago
https://forum.ansible.com/t/403-for-galaxy-api-when-publishing-collection-to-galaxy-ansible-com/1445/8

I don't have acces to the Secrets of this repo and I think I don't have access to threI'm not sure who's holding the credentials for Ansbile Galaxy (https://galaxy.ansible.com/ui/repo/published/equinix/cloud/).

@displague Can you please regenerate the API key and put it to the secrets here?

**Comment by ocobles** [comment]
AG token updated

**Comment by t0mk** [comment]
@ocobles thank you! I re-run the release deployment job and v0.3.0 was created in AG:

https://galaxy.ansible.com/ui/repo/published/equinix/cloud/docs/?version=0.3.0
