### ISSUE TITLE
ci: semantic release GitHub action

### ISSUE THREAD

**Issue by t0mk** [equinix-labs/ansible-collection-equinix#152]
##### SUMMARY
GitHub workflow run on-demand, which will derive new (semantic) version number based on conventional-commits syntax from PRs merged since last release. It should create GitHub release and build and upload to Ansible Galaxy. (We already have workflow for that [0])

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
CI

##### ADDITIONAL INFORMATION
Already present in EM DevRel Projects [1,2]
- [0] https://github.com/equinix-labs/ansible-collection-equinix/blob/main/.github/workflows/release.yml
- [1] https://github.com/equinix/terraform-provider-equinix/blob/main/.github/workflows/release.yml
- [2] https://github.com/equinix/equinix-sdk-go/blob/main/.github/workflows/release.yaml

We're using GH action https://github.com/cycjimmy/semantic-release-action

**Comment by ctreatma** [comment]
Closed by #154
